SELECT 
    tc.TABLE_NAME, 
    kcu.COLUMN_NAME AS PrimaryKeyColumn, 
    rc.CONSTRAINT_NAME AS ForeignKeyName, 
    rcu.TABLE_NAME AS ReferencedTableName, 
    rcu.COLUMN_NAME AS ReferencedColumnName
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
LEFT JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc ON tc.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE rcu ON rc.UNIQUE_CONSTRAINT_NAME = rcu.CONSTRAINT_NAME
WHERE tc.CONSTRAINT_TYPE = 'PRIMARY KEY' OR tc.CONSTRAINT_TYPE = 'FOREIGN KEY'
ORDER BY tc.TABLE_NAME, kcu.COLUMN_NAME;